<a href="https://colab.research.google.com/github/riya-046/Traffic-Analysis-Project/blob/main/01_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving delhi_traffic_features.csv to delhi_traffic_features.csv

In [2]:
import pandas as pd

df = pd.read_csv('delhi_traffic_features.csv')
df.head()

,Trip_ID,start_area,end_area,distance_km,time_of_day,day_of_week,weather_condition,traffic_density_level,road_type,average_speed_kmph
0,TRIP_00001,Vasant Kunj,Kalkaji,9.44,Night,Weekday,Clear,Low,Main Road,37.8
1,TRIP_00002,Greater Kailash,Kalkaji,2.15,Night,Weekend,Clear,Low,Main Road,42.7
2,TRIP_00003,Janakpuri,Model Town,14.54,Morning Peak,Weekday,Rain,High,Inner Road,9.7
3,TRIP_00004,Punjabi Bagh,Dwarka,11.86,Night,Weekday,Clear,Low,Highway,68.5
4,TRIP_00005,Rohini,Chandni Chowk,20.26,Afternoon,Weekday,Fog,Medium,Highway,30.3

In [3]:
df.shape

(4000, 10)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_ID                4000 non-null   object
 1   start_area             4000 non-null   object
 2   end_area               4000 non-null   object
 3   distance_km            4000 non-null   float64
 4   time_of_day            4000 non-null   object
 5   day_of_week            4000 non-null   object
 6   weather_condition      4000 non-null   object
 7   traffic_density_level  4000 non-null   object
 8   road_type              4000 non-null   object
 9   average_speed_kmph     4000 non-null   float64
dtypes: float64(2), object(8)
memory usage: 312.6+ KB

In [5]:
df.isnull().sum()

Trip_ID                  0
start_area               0
end_area                 0
distance_km              0
time_of_day              0
day_of_week              0
weather_condition        0
traffic_density_level    0
road_type                0
average_speed_kmph       0
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.drop(columns=['Trip_ID'], inplace=True)

In [10]:
df.columns

Index(['start_area', 'end_area', 'distance_km', 'time_of_day', 'day_of_week',
       'weather_condition', 'traffic_density_level', 'road_type',
       'average_speed_kmph'],
      dtype='object')

In [11]:
df['time_of_day'] = df['time_of_day'].str.lower().str.strip()
df['day_of_week'] = df['day_of_week'].str.lower().str.strip()
df['weather_condition'] = df['weather_condition'].str.lower().str.strip()
df['road_type'] = df['road_type'].str.lower().str.strip()
df['traffic_density_level'] = df['traffic_density_level'].str.lower().str.strip()

In [12]:
mapping = {
    'low': 1,
    'medium': 2,
    'high': 3
}

df['traffic_density_level'] = df['traffic_density_level'].map(mapping)

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cols = [
    'start_area',
    'end_area',
    'time_of_day',
    'day_of_week',
    'weather_condition',
    'road_type'
]

for col in cols:
    df[col] = le.fit_transform(df[col])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   start_area             4000 non-null   int64
 1   end_area               4000 non-null   int64
 2   distance_km            4000 non-null   float64
 3   time_of_day            4000 non-null   int64
 4   day_of_week            4000 non-null   int64
 5   weather_condition      4000 non-null   int64
 6   traffic_density_level  3021 non-null   float64
 7   road_type              4000 non-null   int64
 8   average_speed_kmph     4000 non-null   float64
dtypes: float64(3), int64(6)
memory usage: 281.4 KB

In [15]:
df.to_csv('cleaned_data.csv', index=False)

In [16]:
from google.colab import files
files.download('cleaned_data.csv')

Data Cleaning Steps:

- Removed duplicates
- Dropped Trip_ID column
- Standardized text columns
- Converted traffic levels to numeric
- Encoded categorical variables