In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
print("all working")

all working

In [9]:
import pandas as pd
df = pd.read_csv('../Data/Raw/futuristic_city_traffic.csv')
df.head()

print("\nShape of dataset (rows, columns):")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types and non-null values:")
print(df.info())

print("\nStatistical summary (numerical columns):")
display(df.describe())

Shape of dataset (rows, columns):
(1219567, 11)

Column names:
['City', 'Vehicle Type', 'Weather', 'Economic Condition', 'Day Of Week', 'Hour Of Day', 'Speed', 'Is Peak Hour', 'Random Event Occurred', 'Energy Consumption', 'Traffic Density']

Data types and non-null values:
<class 'pandas.DataFrame'>
RangeIndex: 1219567 entries, 0 to 1219566
Data columns (total 11 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   City                   1219567 non-null  str
 1   Vehicle Type           1219567 non-null  str
 2   Weather                1219567 non-null  str
 3   Economic Condition     1219567 non-null  str
 4   Day Of Week            1219567 non-null  str
 5   Hour Of Day            1219567 non-null  int64
 6   Speed                  1219567 non-null  float64
 7   Is Peak Hour           1219567 non-null  int64
 8   Random Event Occurred  1219567 non-null  int64
 9   Energy Consumption     1219567 non-null  float64
 10  Traffic Density        1219567 non-null  float64
dtypes: float64(3), int64(3), str(5)
memory usage: 156.8 MB
None

Statistical summary (numerical columns):

,Hour Of Day,Speed,Is Peak Hour,Random Event Occurred,Energy Consumption,Traffic Density
count,1.219567e+06,1.219567e+06,1.219567e+06,1.219567e+06,1.219567e+06,1.219567e+06
mean,1.150817e+01,5.994476e+01,1.546992e-01,4.988738e-02,4.946464e+01,2.770960e-01
std,6.919071e+00,2.663203e+01,3.616178e-01,2.177123e-01,2.528014e+01,2.191019e-01
min,0.000000e+00,6.693400e+00,0.000000e+00,0.000000e+00,4.929600e+00,5.900000e-03
25%,6.000000e+00,3.753310e+01,0.000000e+00,0.000000e+00,2.927395e+01,1.059000e-01
50%,1.200000e+01,5.847110e+01,0.000000e+00,0.000000e+00,4.578260e+01,2.186000e-01
75%,1.700000e+01,8.053455e+01,0.000000e+00,0.000000e+00,6.590550e+01,3.960000e-01
max,2.300000e+01,1.630886e+02,1.000000e+00,1.000000e+00,1.899489e+02,3.377600e+00

In [5]:
import pandas as pd
df = pd.read_csv('../Data/Raw/Traffic.csv')
df.head()

,Time,Date,Day of the week,CarCount,BikeCount,BusCount,TruckCount,Total,Traffic Situation
0,12:00:00 AM,10,Tuesday,31,0,4,4,39,low
1,12:15:00 AM,10,Tuesday,49,0,3,3,55,low
2,12:30:00 AM,10,Tuesday,46,0,3,6,55,low
3,12:45:00 AM,10,Tuesday,51,0,2,5,58,low
4,1:00:00 AM,10,Tuesday,57,6,15,16,94,normal

In [6]:
import pandas as pd
df = pd.read_csv('../Data/Raw/TrafficTwoMonth.csv')
df.head()

,Time,Date,Day of the week,CarCount,BikeCount,BusCount,TruckCount,Total,Traffic Situation
0,12:00:00 AM,10,Tuesday,13,2,2,24,41,normal
1,12:15:00 AM,10,Tuesday,14,1,1,36,52,normal
2,12:30:00 AM,10,Tuesday,10,2,2,32,46,normal
3,12:45:00 AM,10,Tuesday,10,2,2,36,50,normal
4,1:00:00 AM,10,Tuesday,11,2,1,34,48,normal